- hosts: standard-stack
  user: root
  vars:
    username: root
    password: 
    public_key: /root/.ssh/id_rsa.pub
    newrelic_server_license_key: #### YOUR KEY #### 
    bash_history_notification_email: #### YOUR EMAIL ####
  roles:
   - common
   - newrelic
   - bash_history
   - login_alerts
#   - iptables
#   - graylog
