- hosts: standard-stack
  user: root
  vars:
    username: root
    password: 
    public_key: /root/.ssh/id_rsa.pub
  roles:
   - common
#   - newrelic
#   - bash_history
#   - login_alerts 
#   - iptables
#   - graylog
