- hosts: standard-stack
  user: root
  vars:
    username: root
    password: 
    public_key_url: ### YOUR SSH PUBLIC KEY URL ###
    newrelic_server_license_key: ### YOUR NR KEY ###
    bash_history_notification_email: ### YOUR EMAIL ###
  roles:
   - common
   - newrelic
   - bash_history
   - login_alerts
#   - iptables
#   - graylog
