- hosts: standard-stack
  user: root
  vars:
    username: root
    password: 
    public_key: /root/.ssh/id_rsa.pub
    newrelic_license: ####YOUR KEY#####
  roles:
   - common
   - newrelic
#   - bash_history
#   - login_alerts 
#   - iptables
#   - graylog
