- name: Copy graylog config files to rsyslog dir.
  copy: 
    src: https://raw.githubusercontent.com/juanmanavella/sa/master/90-graylog.conf
    dest: /etc/rsyslog.d/Q90-graylog.conf
  notify: reload nginx 
