- apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present 

- apt_repository: repo='deb deb http://apt.newrelic.com/debian/ newrelic non-free' state=present filename='newrelic' update_cache='yes'

- apt: name='newrelic-sysmond' state='present' update_cache='yes'

- name: add NR key
  shell: /usr/sbin/nrsysmond-config --set license_key=
  notify: restart newrelic-sysmond
